# Información del proyecto
sonar.projectKey=psw-pipeline-base
sonar.projectName=PSW Pipeline Base
sonar.projectVersion=0.0.1

# Rutas del código fuente
sonar.sources=src/main/java
sonar.tests=src/test/java

# Configuración de Java
sonar.java.source=17
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# Reportes de cobertura
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Encoding
sonar.sourceEncoding=UTF-8

# Exclusiones
sonar.exclusions=**/model/**,**/config/**
sonar.test.exclusions=**/test/**

# Configuración adicional
sonar.java.coveragePlugin=jacoco
